<?php

/**
 * Application loader script.
 *
 * This file initializes the core application environment:
 * - Checks maintenance mode status
 * - Loads the autoloader
 * - Registers the custom autoloading mechanism
 * - Instantiates the router to process the current request
 *
 * This is the second stage of the bootstrap process, executed after
 * config.php has defined all system constants.
 *
 * @package   Config
 * @author    Alexandr Nikitin
 * @version   16.0
 * @copyright (c) 2026
 */

use \Config\CC as C;

// ============================================================================
// MAINTENANCE MODE CHECK
// ============================================================================

/**
 * Check if engineering works mode is enabled.
 *
 * If ENGINEERING_WORKS is true and the 'DEVELOPER' GET parameter is NOT present,
 * redirect all traffic to the maintenance page (locked.html).
 *
 * The 'DEVELOPER' parameter allows developers to bypass the maintenance page
 * for testing purposes.
 */
if (true === ENGINEERING_WORKS && !isset($_GET['DEVELOPER'])) {
    header('Location: ' . ROOT . 'Application/Layout/locked.html');
    die();
}

// ============================================================================
// AUTOLOADER INITIALIZATION
// ============================================================================

/**
 * Load the generated autoloader class map.
 *
 * Autoloader.php is generated by Application/Tools/createAutoloader.php
 * and contains the complete mapping of all classes to their file paths.
 * It must be regenerated after any class creation, deletion, or movement.
 */
require_once(__DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'Application' . DIRECTORY_SEPARATOR . 'Autoloader.php');

/**
 * Instantiate the autoloader and store it in CC for global access.
 *
 * The autoloader instance is stored statically so it can be used by
 * the custom __loader method for class resolution and dependency loading.
 */
C::$_loader = new \Application\Autoloader();

// ============================================================================
// AUTOLOAD REGISTRATION
// ============================================================================

/**
 * Register the custom autoloader based on AUTOLOAD_MODE.
 *
 * When AUTOLOAD_MODE is set to 1:
 * - Only interfaces and traits are loaded initially
 * - Other classes are loaded on-demand via CC::__loader()
 * - This reduces memory usage and improves performance
 *
 * When AUTOLOAD_MODE is 0 (default fallback):
 * - All classes are loaded during session initialization
 * - Not recommended for production environments
 */
if (AUTOLOAD_MODE == 1) {
    spl_autoload_register(['\\Config\\CC', '__loader']);
}

// ============================================================================
// ROUTER INITIALIZATION
// ============================================================================

/**
 * Instantiate the router to handle the current request.
 *
 * The router:
 * 1. Parses the request URI
 * 2. Determines the module, controller, and action
 * 3. Instantiates the appropriate controller
 * 4. Executes the requested action
 * 5. Renders the response
 *
 * This is the entry point that delegates all HTTP requests to
 * the appropriate application logic.
 */
new \Application\Router();