; ID of current project
; this ID must be exists in the table projects in main database of this Project
cli_project_id = 1

locked = 1

unlock_cookie_name = 'slot-h'
unlock_cookie_value = '666'

; http | https
protocol = https

meta_name = "SLOT-H"
meta_logo = ""
meta_author = "Alexandr Nikitin"
; The meta_description text must be manually added to the tkeys list for translation.
meta_description = "Экосистема для мультипроектных систем на PHP. Один код — множество проектов. Без микросервисов. Без контейнеризации. 15+ лет в продакшене."

meta_google = ""
meta_yandex = ""

db_helper = Mysql

; 0 | 1 - disabled or enabled Cache engine
cache_enable = 0

; Redis [address: 127.0.0.1, port: 6379, attention! engine use cache_name]
; Memcached [address: 127.0.0.1, port: 11211, name not use]
; Mongo [address: 127.0.0.1, port: 27017, attention! engine use cache_name, CACHE_USER, CACHE_PASSWORD]
;   example connections:
;       Redis
;           cache_host = 127.0.0.1
;           cache_port = 6379 ; show default port
;           cache_name = name_of_default_collection
;       Memcached
;           cache_host = 127.0.0.1
;           cache_engine = Memcached
;           cache_port = 11211 ; show default port
;       Mongo
;           cache_engine = Mongo
;           cache_port = 27017 ; show default port
;           CACHE_USER = user
;           CACHE_PASSWORD = user_password
;           cache_name = name_of_base
;           CACHE_COLLECTION = name_of_default_collection
cache_engine = ""
cache_host = ""
cache_port = ""
cache_name = ""

; ID of language in the table languages of current database
core_default_language = 1
; ID of gender in the table persons of current database
core_default_gender = 2

; Mail | Mandrill | Brevo | Smtp (classes in folder Application/Helpers/Mail
mail_engine = ""
mail_apikey = ""
mail_email = ""
mail_from = ""

; Telegram bot
telegram_api_key = ""
telegram_bot_id = ""

; login & password of user, to the usage SMS-service
sms_login = ""
sms_password = ""

; Redis | Sql
queue_server = Sql

; php|php5.6|php7.0 e.t.c - used in the queue server
console_php = php

; default skin
base_skin = 1

default_module = Free
default_controller = Index
default_action = index

view_engine = Bootstrap

yandex_map_apikey = ""
google_map_apikey = ""
map_center = "WORLD"

hash_algorithm = default
main_database = base

socket = ""

[base]
db_engine = Mysql_Mysqli
db_name = start
db_host = localhost
db_port = 3306
db_login = root
db_password = qwerty

[geo]
db_engine = Mysql_Mysqli
db_name = geo_start
db_host = localhost
db_port = 3306
db_login = root
db_password = qwerty
